///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestRailJenkins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestRailJenkinsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0c8dce96-a0b2-4edf-8eca-1e3f343bb269")]
    public partial class TestRailJenkinsRepository : RepoGenBaseFolder
    {
        static TestRailJenkinsRepository instance = new TestRailJenkinsRepository();
        TestRailJenkinsRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder _ranorexvipdatabasetestwebapplicatio;

        /// <summary>
        /// Gets the singleton class instance representing the TestRailJenkinsRepository element repository.
        /// </summary>
        [RepositoryFolder("0c8dce96-a0b2-4edf-8eca-1e3f343bb269")]
        public static TestRailJenkinsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestRailJenkinsRepository() 
            : base("TestRailJenkinsRepository", "/", null, 0, false, "0c8dce96-a0b2-4edf-8eca-1e3f343bb269", ".\\RepositoryImages\\TestRailJenkinsRepository0c8dce96.rximgres")
        {
            _ranorexvipdatabasetestwebapplicatio = new TestRailJenkinsRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0c8dce96-a0b2-4edf-8eca-1e3f343bb269")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatio folder.
        /// </summary>
        [RepositoryFolder("39765ae2-c2e3-44e6-980a-d53db448150b")]
        public virtual TestRailJenkinsRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder RanorexVIPDatabaseTestWebApplicatio
        {
            get { return _ranorexvipdatabasetestwebapplicatio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestRailJenkinsRepositoryFolders
    {
        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatioAppFolder folder.
        /// </summary>
        [RepositoryFolder("39765ae2-c2e3-44e6-980a-d53db448150b")]
        public partial class RanorexVIPDatabaseTestWebApplicatioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _genderInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;
            RepoItemInfo _clearInfo;

            /// <summary>
            /// Creates a new RanorexVIPDatabaseTestWebApplicatio  folder.
            /// </summary>
            public RanorexVIPDatabaseTestWebApplicatioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexVIPDatabaseTestWebApplicatio", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "39765ae2-c2e3-44e6-980a-d53db448150b", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", 30000, null, "29f987d6-2e3a-46d3-a14d-9c95a297bb8b");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", 30000, null, "bd535b7f-cd71-4a57-a6a8-66115aa60d68");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//select[#'Category']/option[@value='Movie']", 30000, null, "604e6da8-e43c-449b-9d9a-4984c46c9d19");
                _genderInfo = new RepoItemInfo(this, "Gender", ".//td[#'gender']//input[@name='Gender' and @type='radio' and @value='male']", 30000, null, "86aea9a6-9082-4ac4-87cf-e1d2c420a9d3");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", 30000, null, "536526c5-1b3f-457d-b12a-09025b445ece");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", 30000, null, "85785a4b-5eb5-44ba-831e-d5d02c7342f6");
                _clearInfo = new RepoItemInfo(this, "Clear", ".//input[#'Clear']", 30000, null, "7e7a07c7-3af5-49d4-8bd8-af82acf6a7d8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("39765ae2-c2e3-44e6-980a-d53db448150b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("39765ae2-c2e3-44e6-980a-d53db448150b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("29f987d6-2e3a-46d3-a14d-9c95a297bb8b")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("29f987d6-2e3a-46d3-a14d-9c95a297bb8b")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("bd535b7f-cd71-4a57-a6a8-66115aa60d68")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("bd535b7f-cd71-4a57-a6a8-66115aa60d68")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("604e6da8-e43c-449b-9d9a-4984c46c9d19")]
            public virtual Ranorex.OptionTag Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("604e6da8-e43c-449b-9d9a-4984c46c9d19")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("86aea9a6-9082-4ac4-87cf-e1d2c420a9d3")]
            public virtual Ranorex.InputTag Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("86aea9a6-9082-4ac4-87cf-e1d2c420a9d3")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("536526c5-1b3f-457d-b12a-09025b445ece")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("536526c5-1b3f-457d-b12a-09025b445ece")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("85785a4b-5eb5-44ba-831e-d5d02c7342f6")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("85785a4b-5eb5-44ba-831e-d5d02c7342f6")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }

            /// <summary>
            /// The Clear item.
            /// </summary>
            [RepositoryItem("7e7a07c7-3af5-49d4-8bd8-af82acf6a7d8")]
            public virtual Ranorex.InputTag Clear
            {
                get
                {
                    return _clearInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Clear item info.
            /// </summary>
            [RepositoryItemInfo("7e7a07c7-3af5-49d4-8bd8-af82acf6a7d8")]
            public virtual RepoItemInfo ClearInfo
            {
                get
                {
                    return _clearInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
